### PR TITLE
testing check

### PR DESCRIPTION
**Pull request by VenkateshBH99**
Updated the UI design

### CODE REVIEW

**Comment by VenkateshBH99** [comment]
Changed the Order UI design

**Comment by VenkateshBH99** [comment]
Don't merge the pull request just review the code

**Comment by VenkateshBH99** [comment]
updated the download button

**Comment by paragjnath** [comment]
@VenkateshBH99  Please format the files.

**Comment by VenkateshBH99** [comment]
@paragjnath  Formatted the code

**Comment by RC-Jay** [comment]
Very Old, testing code

**Pull request closed without merging**
